app_image_analyzer/urls.py
from django.urls import path

from app_image_analyzer.views import UploadAndAnalyzeImageView

app_name = 'analyzer'
urlpatterns = [
    path('', UploadAndAnalyzeImageView.as_view(), name='upload_image'),
]

image_analyzer/urls.py
"""image_analyzer URL Configuration"""
from django.urls import path, include

urlpatterns = [
    path('', include('app_image_analyzer.urls'))
]

app_image_analyzer/forms.py
from django import forms
from django.core.validators import RegexValidator, FileExtensionValidator


class UploadImageForm(forms.Form):
    """
    Форма загрузки изображения и ввода HEX-кода искомого цвета.
    """
    image = forms.ImageField(
        label='Файл изображения',
        validators=[
            FileExtensionValidator(allowed_extensions=(
                'jpg', 'jpeg', 'gif', 'bmp', 'png',
            ))])
    hex_code = forms.CharField(
        max_length=7,
        label='HEX-код искомого цвета',
        required=False,
        validators=[
            RegexValidator(regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')
        ],
        error_messages={
            'invalid': 'Некорректный HEX-код. Примеры: #FFFFFF, #fff, #000'
        },
    )

app_image_analyzer/views.py
import logging

from django.shortcuts import render
from django.views import View

from app_image_analyzer.forms import UploadImageForm
from app_image_analyzer.utils import get_analysis_result

logger = logging.getLogger(__name__)


class UploadAndAnalyzeImageView(View):
    """
    View для загрузки изображения и HEX-кода в html-форму, обработки данных
    и возврата результата анализа на html-страницу.
    """
    upload_image_template = 'app_image_analyzer/upload_image_form.html'
    analysis_result_template = 'app_image_analyzer/analysis_result.html'

    def get(self, request):
        """
        Обработка GET-запроса.
        """
        logger.info('GET request from user')

        form = UploadImageForm()
        context = {
            'form': form,
        }
        return render(request, self.upload_image_template, context=context)

    def post(self, request):
        """
        Обработка POST-запроса.
        """
        logger.info('POST request from user')

        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():

            image = form.cleaned_data.get('image')
            hex_code = form.cleaned_data.get('hex_code')

            logger.info('User upload valid data in form', extra={
                'file_name': image.name,
                'file_size': image.size,
                'hex_code': hex_code,
            })

            black_pixel_count, white_pixel_count, search_color_pixel = \
                get_analysis_result(image_file=image, hex_code=hex_code)
            context = {
                'file_name': image.name,
                'black_pixel_count': black_pixel_count,
                'white_pixel_count': white_pixel_count,
                'search_color': hex_code,
                'search_color_pixel': search_color_pixel,
            }

            logger.info('Return analysis result', extra=context)
            return render(request, self.analysis_result_template,
                          context=context)

        context = {
            'form': form,
        }
        logger.info('User upload not valid data in form')
        return render(request, self.upload_image_template, context=context)

templates/app_image_analyzer/analysis_result.html
{% extends 'base.html' %}

{% block title %}
        Результат анализа
{% endblock %}

{% block content %}
        <div class="mb-4"><h2>Результат анализа</h2></div>
        <p><b>{% if black_pixel_count > white_pixel_count %}
                Черных пикселей больше белых на загруженном изображении
        {% elif black_pixel_count < white_pixel_count %}
                Белых пикселей больше черных на загруженном изображении
        {% else %}
                Одинаковое количество белых и черных пикселей на загруженном изображении
        {% endif %}</b></p>

        {% if search_color %}
                <p><b>А пикселей искомого цвета {{ search_color }}: {{ search_color_pixel }}</b></p>
        {% endif %}
        <p>Имя файла: {{ file_name }}</p>
        <p>Черных пикселей: {{ black_pixel_count }}</p>
        <p>Белых пикселей: {{ white_pixel_count }}</p>
        <hr><p><a href="{% url 'analyzer:upload_image' %}">Вернуться на страницу загрузки изображения</a></p>
{% endblock %}

templates/app_image_analyzer/upload_image_form.html
{% extends 'base.html' %}

{% block title %}
        Загрузка файла изображения
{% endblock %}

{% block content %}
    <div class="mb-4"><h2>Загрузка файла изображения</h2></div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Отправить</button>
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
              crossorigin="anonymous">
        <title>
            {% block title %}
            {% endblock %}
        </title>
    </head>
    <body>
        <div class="container mt-1 ms-1">
            <div class="row">
                <div class="col-6">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>